avoid deprecated ERR_load_crypto_strings API
This function was deprecated in 1.1.0 which setting OpenSSL API compt
to 0x10100000L disables the API.  Trying to build with OpenSSL 1.1.1w
fails now with:
ssherr-libcrypto.c:39:2: error:
  call to undeclared function 'ERR_load_crypto_strings';
  ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   39 |         ERR_load_crypto_strings();
      |         ^

From the OpenSSL CHANGES file:
> However, applications are strongly advised to compile their source files with
> -DOPENSSL_API_COMPAT=0x10100000L, which hides the declarations of all interfaces
> deprecated in 0.9.8, 1.0.0 or the 1.1.0 releases.

Switch to the replacement API which is available in OpenSSL 1.1.1 (the
oldest OpenSSH supports) and all current versions.